
services:
  postgres:
    container_name: feedback_pg
    image: bitnami/postgresql:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=feedback
    volumes:
      - feedback_pg_data:/bitnami/postgresql
  redis:
    container_name: feedback_redis
    image: bitnami/redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - "feedback_redis_data:/bitnami/redis/data"
volumes:
  feedback_pg_data:
  feedback_redis_data: