
services:
  postgres:
    container_name: feedback_pg
    image: bitnami/postgresql:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=feedback
    volumes:
      - feedback_pg_data:/bitnami/postgresql
volumes:
  feedback_pg_data: