spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/feedback
    driver-class-name: org.postgresql.Driver
    username: docker
    password: docker
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  main:
    allow-bean-definition-overriding: true
    log-startup-info: true
logging:
  level:
    org:
      springframework:
        ws:
          server:
            endpoint: DEBUG
      hibernate:
        SQL: debug
        type: trace
      apache:
        cxf: INFO
server:
  port: 8080 # Your server port to development
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,loggers
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
